kind: pipeline
type: docker # 在 Docker 內部執行管道命令
name: python3.9

steps:
- name: greeting
  image: python:3.9.12-alpine
  commands:
  - echo hello
  - echo world
  - apk update \
  - apk add libffi libpq-dev gcc
  - pip install --upgrade pip
  - pip install --upgrade cffi==1.14.0

  #- pip install -r /requirements.txt
  - pip install docker-compose
  - docker-compose run app sh -c "python manage.py test "