language: python
python:
 - "3.9"

services:
 - docker

before_script: 
 - pip install docker-compose


script: 
  #- docker-compose build
  - docker-compose run app sh -c "python manage.py test "
  - docker build -t 12cloud/pharmxbackend .
